package com.geekbrains.db.model;

import lombok.Data;

@Data
public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    private Integer id;

    public Products(Integer id, String title, Integer price, Integer categoryId) {
        this.id = id;
        this.title = title;
        this.price = price;
        this.categoryId = categoryId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.title
     *
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.category_id
     *
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.title
     *
     * @return the value of products.title
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.title
     *
     * @param title the value for products.title
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.category_id
     *
     * @return the value of products.category_id
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.category_id
     *
     * @param categoryId the value for products.category_id
     * @mbg.generated Sun Nov 28 13:55:54 MSK 2021
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

}